# Generated by Django 5.1.6 on 2025-03-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_alter_usermeta_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeta',
            name='user',
        ),
        migrations.AddField(
            model_name='usermeta',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
